### ISSUE TITLE
Use `RPC_URL` instead of `ALCHEMY_KEY` in env variable

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/morpho-blue-deployment#20]
It permits you to use other service or self hosted node to deploy the contracts.

**Comment by Rubilmax** [comment]
Do we have the use of it? Otherwise it's overkill
I prefer the canonical way of doing `yarn deploy:morpho ethereum` over `RPC_URL=... yarn deploy:morpho` because you get built-in support for all networks supported by foundry (you don't actually have to specify a rpc URL in foundry.toml)

**Comment by julien-devatom** [comment]
Yes, but in fact: 
- alchemy apps linked with one key are network specific
- so you need to change the alchemy key each time you change network
- so it is not more complex (even easier) to use full RPC env variable
- to mitigate, I suggest to use `MAINNET_RPC_URL`, `POLYGON_RPC_URL` etc

**Comment by julien-devatom** [comment]
Why is it closed? The discussion is still open. It is not a strong requirement, but I'm curious to have your opinion @Rubilmax  on why changing `ALCHEMY_KEY` is more straightforward than changing RPC_URL (and btw keeping the possibility to have one RPC per network)

**Comment by Rubilmax** [comment]
This discussion was closed because a fix was applied, see latest code and README

**Comment by julien-devatom** [comment]
Ok seems weird to me to keep the `ALCHEMY_KEY` options but no big deal, I'm closing it

**Comment by Rubilmax** [comment]
Ethereum, Goerli & Sepolia still use it ^^ simpler to minimize changes and keep backward-compatibility, even if it is not much
